---
title: "QTM 385 Individual Causal Effects"
author: "Elisha Cohen"
date: "Spring 2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Overview

Modern approaches to causal inference focus on estimating average treatment effects, but in everyday life and in fields like business, the social sciences, and medicine, we are often interested in treatment effects for individuals. This course surveys estimation and inference techniques for individual treatment effects from the classical (Mill’s methods) to the modern (synthetic control type methods). Topics covered include a review of methods for average treatment effects, frequentist and Bayesian approaches, prediction intervals, and permutation methods. Big data methods using multiple treated units are omitted from this course. While the course will emphasize the mathematical foundations of these concepts, each topic will also cover the implementation of the relevant methods in the statistical program R.

## Syllabus

[<i class="fa fa-file-pdf-o" aria-hidden="true"></i> PDF][syll-pdf]&ensp;

[syll-pdf]: /PDFs/QTM385_ITE_syllabus_SP22.pdf
